### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by yuqiyuqitan** [igordot/nichexplorer#1]
Hi,

Thanks for the great work! I am very interested in the O3 cluster. I was wondering if it is possible to share the clustering information or the metadata with me?

Thanks,
Yuqi

**Comment by igordot** [comment]
Thank you for your interest in our data. The metadata table that includes cells with their cluster annotation is available on GEO: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE108nnn/GSE108891/suppl/GSE108891_metadata.csv.gz

**Comment by yuqiyuqitan** [comment]
Thank you very much!
