### ISSUE TITLE
BM microenvironment overall counts matrix

### ISSUE THREAD

**Issue by alecorr** [igordot/nichexplorer#2]
Hi,

Thanks for making this data/tool available!

I might have missed it, but is there anywhere I can get access to an overall counts matrix from the BM microenvironment seurat object used to generate the tsne in your nichExplorer browser?

I've seen that the raw sequencing data and expression-count data available on GEO [(GSE108892)](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE108892), but the files are split by experiment and I'm slightly confused as to which samples I would need to integrate to generate the end result seen in the tsne.

Thanks!
Alex

**Comment by igordot** [comment]
Thanks for your interest in the data.

As you mentioned, the raw counts matrix is available on GEO. There is a one for each sample, so you would need to merge them. The metadata table is also on GEO and contains all the cells after filtering with their tSNE coordinates.
